version: "3.9"
services:
  stats:
    image: sts-stats:latest
    build: ./stats
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    volumes:
      - ./stats:/app
  auth:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    ports:
      - "8502:4180"
    links:
      - "stats:stats"
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET
      - OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_PROVIDER=github
      - OAUTH2_PROXY_PASS_USER_HEADERS=true
      - OAUTH2_PROXY_UPSTREAMS=http://stats:8501
      - OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE=/app/allowed_emails.txt
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_SCOPE=user:email
    volumes:
      - ./data/auth:/app