version: "3.9"
services:
  db:
    image: postgres:15
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "18592:5432"
    environment:
    - POSTGRES_PASSWORD
    shm_size: 256MB
    command: -c fsync=off
  jupyter:
    image: jupyter/scipy-notebook
    ports:
    - "8888:8888"
    environment:
    - POSTGRES_PASSWORD
    volumes:
    - C:/Users/bindernews/Projects/sts-metrics/:/home/jovyan/work
    links:
    - "db:database"

volumes:
  db-data: