version: "3.9"
services:
  db:
    image: postgres:15
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "18592:5432"
    environment:
    - POSTGRES_PASSWORD
    shm_size: 256MB
    command: -c fsync=off
  stats:
    image: sts-stats:latest
    build: ./stats
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=database:5432
    links:
      - "db:database"

volumes:
  db-data: